controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [abb_robot_1/joint_1, abb_robot_1/joint_2, abb_robot_1/joint_3, abb_robot_1/joint_4, abb_robot_1/joint_5, abb_robot_1/joint_6]

  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [abb_robot_2/joint_1, abb_robot_2/joint_2, abb_robot_2/joint_3, abb_robot_2/joint_4, abb_robot_2/joint_5, abb_robot_2/joint_6]

  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [abb_robot_3/joint_1, abb_robot_3/joint_2, abb_robot_3/joint_3, abb_robot_3/joint_4, abb_robot_3/joint_5, abb_robot_3/joint_6]

  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

    
