controller_list:
  # - name: fake_manipulator_controller
  #   joints:
  #     - joint_1
  #     - joint_2
  #     - joint_3
  #     - joint_4
  #     - joint_5
  #     - joint_6

  - name: fake_robot1_manipulator_controller
    joints:
      - abb_robot_1/joint_1
      - abb_robot_1/joint_2
      - abb_robot_1/joint_3
      - abb_robot_1/joint_4
      - abb_robot_1/joint_5
      - abb_robot_1/joint_6

  - name: fake_robot2_manipulator_controller
    joints:
      - abb_robot_2/joint_1
      - abb_robot_2/joint_2
      - abb_robot_2/joint_3
      - abb_robot_2/joint_4
      - abb_robot_2/joint_5
      - abb_robot_2/joint_6

  - name: fake_robot3_manipulator_controller
    joints:
      - abb_robot_3/joint_1
      - abb_robot_3/joint_2
      - abb_robot_3/joint_3
      - abb_robot_3/joint_4
      - abb_robot_3/joint_5
      - abb_robot_3/joint_6